-- -- CLIENT (id_client#, nume, email, tip_client)
-- -- VALIDATOR (id_client#*, nivel_validare)
-- -- NFT_CREATOR (id_client#*, portofoliu_link)
-- -- ANALITIC (id_client#*, specializare)
-- -- BLOCKCHAIN (id_blockchain#, nume_blockchain, versiune)
-- -- BLOCK (id_block#, timestamp, id_blockchain*, id_miner*, prev_block)
-- -- MINER (id_miner#, nume, experiență_ani)
-- -- TRANZACTIE (id_tranzactie#, valoare, data, id_client*, id_moneda*, id_block*)
-- -- MONEDA (id_moneda#, nume_moneda, simbol)
-- -- NFT (id_nft#, titlu, descriere, id_moneda*)
-- -- SMART_CONTRACT (id_smart_contract#, cod_contract, id_nft*)
-- -- LICITATIE (id_licitatie#, data_start, data_sfarsit)
-- -- OFERTA (id_bid#, valoare, id_licitatie*, id_client*, timestamp)
-- --
DROP TABLE oferta;
DROP TABLE licitatie;
-- DROP TABLE smart_contract;
DROP TABLE nft;
DROP TABLE tranzactie;
DROP TABLE block;
DROP TABLE miner;
DROP TABLE moneda;
DROP TABLE blockchain;
DROP TABLE analitic;
DROP TABLE nft_creator;
DROP TABLE validator;
DROP TABLE client;

DROP SEQUENCE seq_client;
DROP SEQUENCE seq_validator;
DROP SEQUENCE seq_nft_creator;
DROP SEQUENCE seq_analitic;
DROP SEQUENCE seq_blockchain;
DROP SEQUENCE seq_miner;
DROP SEQUENCE seq_block;
DROP SEQUENCE seq_moneda;
DROP SEQUENCE seq_tranzactie;
DROP SEQUENCE seq_nft;
DROP SEQUENCE seq_smart_contract;
DROP SEQUENCE seq_licitatie;
DROP SEQUENCE seq_oferta;


-- Secvențe pentru identificatori primari (opțional, dacă nu folosești IDENTITY)

CREATE SEQUENCE seq_client START WITH 1;
CREATE SEQUENCE seq_validator START WITH 1;
CREATE SEQUENCE seq_nft_creator START WITH 1;
CREATE SEQUENCE seq_analitic START WITH 1;

CREATE SEQUENCE seq_blockchain START WITH 1;
CREATE SEQUENCE seq_miner START WITH 1;
CREATE SEQUENCE seq_block START WITH 1;

CREATE SEQUENCE seq_moneda START WITH 1;
CREATE SEQUENCE seq_tranzactie START WITH 1;
CREATE SEQUENCE seq_nft START WITH 1;
CREATE SEQUENCE seq_smart_contract START WITH 1;

CREATE SEQUENCE seq_licitatie START WITH 1;
CREATE SEQUENCE seq_oferta START WITH 1;


--CLIENT (id_client#, nume, email, tip_client)
CREATE TABLE client (
    id_client NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    tip_client VARCHAR2(50)
);

--VALIDATOR (id_client#*, nivel_validare)
CREATE TABLE validator (
    id_client NUMBER PRIMARY KEY,
    nivel_validare NUMBER,
    FOREIGN KEY (id_client) REFERENCES client(id_client)
);

--NFT_CREATOR (id_client#*, portofoliu_link)
CREATE TABLE nft_creator (
    id_client NUMBER PRIMARY KEY,
    portofoliu_link VARCHAR2(255),
    FOREIGN KEY (id_client) REFERENCES client(id_client)
);

--ANALITIC (id_client#*, specializare)
CREATE TABLE analitic (
    id_client NUMBER PRIMARY KEY,
    specializare VARCHAR2(100),
    FOREIGN KEY (id_client) REFERENCES client(id_client)
);

--BLOCKCHAIN (id_blockchain#, nume_blockchain, versiune)
CREATE TABLE blockchain (
    id_blockchain NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_blockchain VARCHAR2(100) NOT NULL,
    versiune VARCHAR2(10)
);

--MINER (id_miner#, nume, experiență_ani)
CREATE TABLE miner (
    id_miner NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL,
    experienta_ani NUMBER CHECK (experienta_ani >= 0)
);

--BLOCK (id_block#, timestamp, id_blockchain*, id_miner*, prev_block)
CREATE TABLE block (
    id_block NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    id_blockchain NUMBER,
    id_miner NUMBER,
    prev_block NUMBER,
    FOREIGN KEY (id_blockchain) REFERENCES blockchain(id_blockchain),
    FOREIGN KEY (id_miner) REFERENCES miner(id_miner),
    FOREIGN KEY (prev_block) REFERENCES block(id_block)
);

--MONEDA (id_moneda#, nume_moneda, simbol)
CREATE TABLE moneda (
    id_moneda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_moneda VARCHAR2(50),
    simbol VARCHAR2(10)
);

--TRANZACTIE (id_tranzactie#, valoare, data, id_client*, id_moneda*, id_block*)
CREATE TABLE tranzactie (
    id_tranzactie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valoare DECIMAL(15,2) CHECK (valoare >= 0),
    data DATE NOT NULL,
    id_client NUMBER,
    id_moneda NUMBER,
    id_block NUMBER,
    FOREIGN KEY (id_client) REFERENCES client(id_client),
    FOREIGN KEY (id_moneda) REFERENCES moneda(id_moneda),
    FOREIGN KEY (id_block) REFERENCES block(id_block)
);

--NFT (id_nft#, titlu, descriere, id_moneda*)
CREATE TABLE nft (
    id_nft NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titlu VARCHAR2(100) NOT NULL,
    descriere CLOB,
    id_moneda NUMBER,
    FOREIGN KEY (id_moneda) REFERENCES moneda(id_moneda)
);

--SMART_CONTRACT (id_smart_contract#, cod_contract, id_nft*)
CREATE TABLE smart_contract (
    id_smart_contract NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_contract CLOB NOT NULL,
    id_nft NUMBER UNIQUE,
    FOREIGN KEY (id_nft) REFERENCES nft(id_nft)
);

--LICITATIE (id_licitatie#, data_start, data_sfarsit)
CREATE TABLE licitatie (
    id_licitatie NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_start TIMESTAMP NOT NULL,
    data_sfarsit TIMESTAMP NOT NULL
);

--OFERTA (id_oferta#, valoare, id_licitatie*, id_client*, timestamp)
CREATE TABLE oferta (
    id_oferta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valoare DECIMAL(15,2) CHECK (valoare >= 0),
    id_licitatie NUMBER,
    id_client NUMBER,
    timestamp TIMESTAMP NOT NULL,
    FOREIGN KEY (id_licitatie) REFERENCES licitatie(id_licitatie),
    FOREIGN KEY (id_client) REFERENCES client(id_client)
);
-- CLIENT
INSERT INTO client (id_client, nume, email, tip_client) VALUES (seq_client.NEXTVAL, 'Alex Popescu', 'alex@email.com', 'validator');
INSERT INTO client (id_client, nume, email, tip_client) VALUES (seq_client.NEXTVAL, 'Maria Ionescu', 'maria@email.com', 'nft_creator');
INSERT INTO client (id_client, nume, email, tip_client) VALUES (seq_client.NEXTVAL, 'Andrei Georgescu', 'andrei@email.com', 'analitic');
INSERT INTO client (id_client, nume, email, tip_client) VALUES (seq_client.NEXTVAL, 'Ioana Dinu', 'ioana@email.com', 'nft_creator');
INSERT INTO client (id_client, nume, email, tip_client) VALUES (seq_client.NEXTVAL, 'Radu Matei', 'radu@email.com', 'validator');

-- BLOCKCHAIN
INSERT INTO blockchain (id_blockchain, nume_blockchain, versiune) VALUES (seq_blockchain.NEXTVAL, 'Ethereum', '1.0');
INSERT INTO blockchain (id_blockchain, nume_blockchain, versiune) VALUES (seq_blockchain.NEXTVAL, 'Binance Smart Chain', '1.2');
INSERT INTO blockchain (id_blockchain, nume_blockchain, versiune) VALUES (seq_blockchain.NEXTVAL, 'Solana', '1.5');
INSERT INTO blockchain (id_blockchain, nume_blockchain, versiune) VALUES (seq_blockchain.NEXTVAL, 'Polygon', '1.1');
INSERT INTO blockchain (id_blockchain, nume_blockchain, versiune) VALUES (seq_blockchain.NEXTVAL, 'Avalanche', '1.3');

-- MINER
INSERT INTO miner (id_miner, nume, experienta_ani) VALUES (seq_miner.NEXTVAL, 'Miner A', 3);
INSERT INTO miner (id_miner, nume, experienta_ani) VALUES (seq_miner.NEXTVAL, 'Miner B', 5);
INSERT INTO miner (id_miner, nume, experienta_ani) VALUES (seq_miner.NEXTVAL, 'Miner C', 2);
INSERT INTO miner (id_miner, nume, experienta_ani) VALUES (seq_miner.NEXTVAL, 'Miner D', 7);
INSERT INTO miner (id_miner, nume, experienta_ani) VALUES (seq_miner.NEXTVAL, 'Miner E', 4);

-- MONEDA
INSERT INTO moneda (id_moneda, nume_moneda, simbol) VALUES (seq_moneda.NEXTVAL, 'Ethereum', 'ETH');
INSERT INTO moneda (id_moneda, nume_moneda, simbol) VALUES (seq_moneda.NEXTVAL, 'Bitcoin', 'BTC');
INSERT INTO moneda (id_moneda, nume_moneda, simbol) VALUES (seq_moneda.NEXTVAL, 'BNB', 'BNB');
INSERT INTO moneda (id_moneda, nume_moneda, simbol) VALUES (seq_moneda.NEXTVAL, 'Solana', 'SOL');
INSERT INTO moneda (id_moneda, nume_moneda, simbol) VALUES (seq_moneda.NEXTVAL, 'Matic', 'MATIC');

-- VALIDATOR
INSERT INTO validator (id_client, nivel_validare) VALUES (1, 3);
INSERT INTO validator (id_client, nivel_validare) VALUES (5, 2);

-- NFT_CREATOR
INSERT INTO nft_creator (id_client, portofoliu_link) VALUES (2, 'https://portfolio.maria.io');
INSERT INTO nft_creator (id_client, portofoliu_link) VALUES (4, 'https://ioana-nfts.art');

-- ANALITIC
INSERT INTO analitic (id_client, specializare) VALUES (3, 'market trends');

-- BLOCK (folosește prev_block NULL pentru început)
INSERT INTO block (id_block, timestamp, id_blockchain, id_miner, prev_block) VALUES (seq_block.NEXTVAL, SYSTIMESTAMP, 1, 1, NULL);
INSERT INTO block (id_block, timestamp, id_blockchain, id_miner, prev_block) VALUES (seq_block.NEXTVAL, SYSTIMESTAMP, 1, 2, 1);
INSERT INTO block (id_block, timestamp, id_blockchain, id_miner, prev_block) VALUES (seq_block.NEXTVAL, SYSTIMESTAMP, 2, 3, 2);
INSERT INTO block (id_block, timestamp, id_blockchain, id_miner, prev_block) VALUES (seq_block.NEXTVAL, SYSTIMESTAMP, 3, 4, 3);
INSERT INTO block (id_block, timestamp, id_blockchain, id_miner, prev_block) VALUES (seq_block.NEXTVAL, SYSTIMESTAMP, 4, 5, 4);

-- TRANZACTIE
INSERT INTO tranzactie (id_tranzactie, valoare, data, id_client, id_moneda, id_block) VALUES (seq_tranzactie.NEXTVAL, 1500.50, SYSDATE, 1, 1, 1);
INSERT INTO tranzactie (id_tranzactie, valoare, data, id_client, id_moneda, id_block) VALUES (seq_tranzactie.NEXTVAL, 0.05, SYSDATE, 2, 2, 2);
INSERT INTO tranzactie (id_tranzactie, valoare, data, id_client, id_moneda, id_block) VALUES (seq_tranzactie.NEXTVAL, 300.75, SYSDATE, 3, 3, 3);
INSERT INTO tranzactie (id_tranzactie, valoare, data, id_client, id_moneda, id_block) VALUES (seq_tranzactie.NEXTVAL, 800.00, SYSDATE, 4, 4, 4);
INSERT INTO tranzactie (id_tranzactie, valoare, data, id_client, id_moneda, id_block) VALUES (seq_tranzactie.NEXTVAL, 120.40, SYSDATE, 5, 5, 5);

-- NFT
INSERT INTO nft (id_nft, titlu, descriere, id_moneda) VALUES (seq_nft.NEXTVAL, 'CryptoArt1', 'O operă digitală abstractă', 1);
INSERT INTO nft (id_nft, titlu, descriere, id_moneda) VALUES (seq_nft.NEXTVAL, 'PixelWarrior', 'Un NFT pixelat', 2);
INSERT INTO nft (id_nft, titlu, descriere, id_moneda) VALUES (seq_nft.NEXTVAL, 'Virtual Landscape', 'Peisaj VR', 3);
INSERT INTO nft (id_nft, titlu, descriere, id_moneda) VALUES (seq_nft.NEXTVAL, 'MonaChain', 'Replica Mona Lisa digitală', 4);
INSERT INTO nft (id_nft, titlu, descriere, id_moneda) VALUES (seq_nft.NEXTVAL, 'AlienCat', 'Pisică extraterestră', 5);

-- SMART_CONTRACT
INSERT INTO smart_contract (id_smart_contract, cod_contract, id_nft) VALUES (seq_smart_contract.NEXTVAL, 'contract code 1', 1);
INSERT INTO smart_contract (id_smart_contract, cod_contract, id_nft) VALUES (seq_smart_contract.NEXTVAL, 'contract code 2', 2);
INSERT INTO smart_contract (id_smart_contract, cod_contract, id_nft) VALUES (seq_smart_contract.NEXTVAL, 'contract code 3', 3);
INSERT INTO smart_contract (id_smart_contract, cod_contract, id_nft) VALUES (seq_smart_contract.NEXTVAL, 'contract code 4', 4);
INSERT INTO smart_contract (id_smart_contract, cod_contract, id_nft) VALUES (seq_smart_contract.NEXTVAL, 'contract code 5', 5);

-- LICITATIE
INSERT INTO licitatie (id_licitatie, data_start, data_sfarsit) VALUES (seq_licitatie.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + 3);
INSERT INTO licitatie (id_licitatie, data_start, data_sfarsit) VALUES (seq_licitatie.NEXTVAL, SYSTIMESTAMP, SYSTIMESTAMP + 5);

-- OFERTA (10 inserări)
BEGIN
  FOR i IN 1..10 LOOP
    INSERT INTO oferta (id_oferta, valoare, id_licitatie, id_client, timestamp)
    VALUES (seq_oferta.NEXTVAL, 100 + i * 10, MOD(i,2)+1, MOD(i,5)+1, SYSTIMESTAMP);
  END LOOP;
END;